version: '2'

services:
  app:
    image: 'logistics:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=local

  db:
    image: 'postgres:13.1-alpine'
    container_name: logistics_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin